openapi: 3.0.0
info:
  title: Pet Store API
  description: 这是一个示例 Pet Store API，用于演示 swagger-ts-toolkit 的功能
  version: 1.0.0
  contact:
    name: API Support
    email: support@petstore.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.petstore.com/v1
    description: 生产环境
  - url: https://dev-api.petstore.com/v1
    description: 开发环境

paths:
  /pets:
    get:
      operationId: getPets
      summary: 获取宠物列表
      description: 返回所有宠物的列表，支持分页和筛选
      parameters:
        - name: limit
          in: query
          description: 返回结果的最大数量
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: 跳过的记录数
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: status
          in: query
          description: 按状态筛选宠物
          required: false
          schema:
            type: string
            enum: [available, pending, sold]
      responses:
        '200':
          description: 成功返回宠物列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Pet'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 服务器内部错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    post:
      operationId: createPet
      summary: 创建新宠物
      description: 添加一个新的宠物到商店
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePetRequest'
      responses:
        '201':
          description: 宠物创建成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Pet'
                  message:
                    type: string
                    example: "宠物创建成功"
        '400':
          description: 请求数据无效
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: 数据验证失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'

  /pets/{petId}:
    get:
      operationId: getPetById
      summary: 根据ID获取宠物信息
      description: 返回指定ID的宠物详细信息
      parameters:
        - name: petId
          in: path
          required: true
          description: 宠物ID
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: 成功返回宠物信息
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Pet'
        '404':
          description: 宠物不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    put:
      operationId: updatePet
      summary: 更新宠物信息
      description: 更新指定ID的宠物信息
      parameters:
        - name: petId
          in: path
          required: true
          description: 宠物ID
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePetRequest'
      responses:
        '200':
          description: 宠物信息更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Pet'
                  message:
                    type: string
        '404':
          description: 宠物不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    delete:
      operationId: deletePet
      summary: 删除宠物
      description: 从商店中删除指定的宠物
      parameters:
        - name: petId
          in: path
          required: true
          description: 宠物ID
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 宠物删除成功
        '404':
          description: 宠物不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users:
    get:
      operationId: getUsers
      summary: 获取用户列表
      description: 返回所有用户的列表
      responses:
        '200':
          description: 成功返回用户列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
    
    post:
      operationId: createUser
      summary: 创建新用户
      description: 注册一个新用户
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: 用户创建成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/User'

  /users/{userId}:
    get:
      operationId: getUserById
      summary: 根据ID获取用户信息
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功返回用户信息
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/User'

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
        - category
        - status
      properties:
        id:
          type: integer
          format: int64
          description: 宠物ID
          example: 1
        name:
          type: string
          description: 宠物名称
          example: "小白"
          minLength: 1
          maxLength: 50
        category:
          $ref: '#/components/schemas/Category'
        photoUrls:
          type: array
          description: 宠物照片URL列表
          items:
            type: string
            format: uri
          example: ["https://example.com/photo1.jpg", "https://example.com/photo2.jpg"]
        tags:
          type: array
          description: 宠物标签
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: 宠物状态
          enum: [available, pending, sold]
          example: "available"
        price:
          type: number
          format: decimal
          description: 宠物价格
          minimum: 0
          example: 299.99
        birthDate:
          type: string
          format: date
          description: 出生日期
          example: "2023-01-15"
        createdAt:
          type: string
          format: date-time
          description: 创建时间
          example: "2024-01-01T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: 更新时间
          example: "2024-01-01T10:00:00Z"

    CreatePetRequest:
      type: object
      required:
        - name
        - categoryId
        - status
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 50
          example: "小白"
        categoryId:
          type: integer
          format: int64
          example: 1
        photoUrls:
          type: array
          items:
            type: string
            format: uri
        tagIds:
          type: array
          items:
            type: integer
            format: int64
        status:
          type: string
          enum: [available, pending, sold]
          default: "available"
        price:
          type: number
          format: decimal
          minimum: 0
        birthDate:
          type: string
          format: date

    UpdatePetRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 50
        categoryId:
          type: integer
          format: int64
        photoUrls:
          type: array
          items:
            type: string
            format: uri
        tagIds:
          type: array
          items:
            type: integer
            format: int64
        status:
          type: string
          enum: [available, pending, sold]
        price:
          type: number
          format: decimal
          minimum: 0

    User:
      type: object
      required:
        - id
        - username
        - email
      properties:
        id:
          type: integer
          format: int64
          description: 用户ID
          example: 1
        username:
          type: string
          description: 用户名
          example: "john_doe"
          minLength: 3
          maxLength: 20
        firstName:
          type: string
          description: 名
          example: "John"
        lastName:
          type: string
          description: 姓
          example: "Doe"
        email:
          type: string
          format: email
          description: 邮箱地址
          example: "john@example.com"
        phone:
          type: string
          description: 电话号码
          example: "+1234567890"
        userStatus:
          type: integer
          format: int32
          description: 用户状态
          example: 1
        avatar:
          type: string
          format: uri
          description: 头像URL
          example: "https://example.com/avatar.jpg"
        createdAt:
          type: string
          format: date-time
          example: "2024-01-01T10:00:00Z"

    CreateUserRequest:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 20
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
          description: 密码（至少8位）
        phone:
          type: string

    Category:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          description: 分类ID
          example: 1
        name:
          type: string
          description: 分类名称
          example: "狗"

    Tag:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          description: 标签ID
          example: 1
        name:
          type: string
          description: 标签名称
          example: "可爱"

    Pagination:
      type: object
      properties:
        total:
          type: integer
          description: 总记录数
          example: 100
        limit:
          type: integer
          description: 每页记录数
          example: 20
        offset:
          type: integer
          description: 跳过的记录数
          example: 0
        hasMore:
          type: boolean
          description: 是否有更多数据
          example: true

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: 错误代码
          example: 400
        message:
          type: string
          description: 错误信息
          example: "请求参数错误"
        details:
          type: string
          description: 详细错误信息
          example: "参数 'limit' 必须是正整数"

    ValidationError:
      type: object
      required:
        - code
        - message
        - errors
      properties:
        code:
          type: integer
          example: 422
        message:
          type: string
          example: "数据验证失败"
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                example: "name"
              message:
                type: string
                example: "名称不能为空"